/* Automatically generated by tree-sitter v0.25.1 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 125
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 56
#define ALIAS_COUNT 0
#define TOKEN_COUNT 32
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 4
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_line_comment = 1,
  anon_sym_extern = 2,
  anon_sym_task = 3,
  anon_sym_DASH_GT = 4,
  anon_sym_SEMI = 5,
  anon_sym_global = 6,
  anon_sym_COLON = 7,
  anon_sym_use = 8,
  anon_sym_LPAREN = 9,
  anon_sym_COMMA = 10,
  anon_sym_RPAREN = 11,
  anon_sym_LBRACE = 12,
  anon_sym_RBRACE = 13,
  anon_sym_EQ = 14,
  anon_sym_struct = 15,
  anon_sym_enum = 16,
  anon_sym_AMP = 17,
  anon_sym_STAR = 18,
  anon_sym_DASH = 19,
  anon_sym_return = 20,
  anon_sym_schedule = 21,
  anon_sym_every = 22,
  anon_sym_let = 23,
  anon_sym_uninit = 24,
  anon_sym_bool = 25,
  aux_sym_type_token1 = 26,
  anon_sym_LBRACK = 27,
  anon_sym_RBRACK = 28,
  sym_ident = 29,
  sym_string = 30,
  sym_int = 31,
  sym_source_file = 32,
  sym__decl = 33,
  sym_extern_task = 34,
  sym_extern_global = 35,
  sym_use = 36,
  sym_task = 37,
  sym_param_list = 38,
  sym_param_ty_list = 39,
  sym_task_body = 40,
  sym_global = 41,
  sym_struct = 42,
  sym_enum = 43,
  sym_expr = 44,
  sym_call = 45,
  sym_stmt = 46,
  sym_let = 47,
  sym_uninit = 48,
  sym_type = 49,
  sym_literal = 50,
  aux_sym_source_file_repeat1 = 51,
  aux_sym_param_list_repeat1 = 52,
  aux_sym_param_ty_list_repeat1 = 53,
  aux_sym_task_body_repeat1 = 54,
  aux_sym_call_repeat1 = 55,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_line_comment] = "line_comment",
  [anon_sym_extern] = "extern",
  [anon_sym_task] = "task",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_SEMI] = ";",
  [anon_sym_global] = "global",
  [anon_sym_COLON] = ":",
  [anon_sym_use] = "use",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_EQ] = "=",
  [anon_sym_struct] = "struct",
  [anon_sym_enum] = "enum",
  [anon_sym_AMP] = "&",
  [anon_sym_STAR] = "*",
  [anon_sym_DASH] = "-",
  [anon_sym_return] = "return",
  [anon_sym_schedule] = "schedule",
  [anon_sym_every] = "every",
  [anon_sym_let] = "let",
  [anon_sym_uninit] = "uninit",
  [anon_sym_bool] = "bool",
  [aux_sym_type_token1] = "type_token1",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym_ident] = "ident",
  [sym_string] = "string",
  [sym_int] = "int",
  [sym_source_file] = "source_file",
  [sym__decl] = "_decl",
  [sym_extern_task] = "extern_task",
  [sym_extern_global] = "extern_global",
  [sym_use] = "use",
  [sym_task] = "task",
  [sym_param_list] = "param_list",
  [sym_param_ty_list] = "param_ty_list",
  [sym_task_body] = "task_body",
  [sym_global] = "global",
  [sym_struct] = "struct",
  [sym_enum] = "enum",
  [sym_expr] = "expr",
  [sym_call] = "call",
  [sym_stmt] = "stmt",
  [sym_let] = "let",
  [sym_uninit] = "uninit",
  [sym_type] = "type",
  [sym_literal] = "literal",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_param_list_repeat1] = "param_list_repeat1",
  [aux_sym_param_ty_list_repeat1] = "param_ty_list_repeat1",
  [aux_sym_task_body_repeat1] = "task_body_repeat1",
  [aux_sym_call_repeat1] = "call_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_line_comment] = sym_line_comment,
  [anon_sym_extern] = anon_sym_extern,
  [anon_sym_task] = anon_sym_task,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_global] = anon_sym_global,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_use] = anon_sym_use,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_struct] = anon_sym_struct,
  [anon_sym_enum] = anon_sym_enum,
  [anon_sym_AMP] = anon_sym_AMP,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_return] = anon_sym_return,
  [anon_sym_schedule] = anon_sym_schedule,
  [anon_sym_every] = anon_sym_every,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_uninit] = anon_sym_uninit,
  [anon_sym_bool] = anon_sym_bool,
  [aux_sym_type_token1] = aux_sym_type_token1,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_ident] = sym_ident,
  [sym_string] = sym_string,
  [sym_int] = sym_int,
  [sym_source_file] = sym_source_file,
  [sym__decl] = sym__decl,
  [sym_extern_task] = sym_extern_task,
  [sym_extern_global] = sym_extern_global,
  [sym_use] = sym_use,
  [sym_task] = sym_task,
  [sym_param_list] = sym_param_list,
  [sym_param_ty_list] = sym_param_ty_list,
  [sym_task_body] = sym_task_body,
  [sym_global] = sym_global,
  [sym_struct] = sym_struct,
  [sym_enum] = sym_enum,
  [sym_expr] = sym_expr,
  [sym_call] = sym_call,
  [sym_stmt] = sym_stmt,
  [sym_let] = sym_let,
  [sym_uninit] = sym_uninit,
  [sym_type] = sym_type,
  [sym_literal] = sym_literal,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_param_list_repeat1] = aux_sym_param_list_repeat1,
  [aux_sym_param_ty_list_repeat1] = aux_sym_param_ty_list_repeat1,
  [aux_sym_task_body_repeat1] = aux_sym_task_body_repeat1,
  [aux_sym_call_repeat1] = aux_sym_call_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_extern] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_task] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_global] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_use] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_struct] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_enum] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_return] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_schedule] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_every] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_uninit] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_bool] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_type_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_ident] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_int] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__decl] = {
    .visible = false,
    .named = true,
  },
  [sym_extern_task] = {
    .visible = true,
    .named = true,
  },
  [sym_extern_global] = {
    .visible = true,
    .named = true,
  },
  [sym_use] = {
    .visible = true,
    .named = true,
  },
  [sym_task] = {
    .visible = true,
    .named = true,
  },
  [sym_param_list] = {
    .visible = true,
    .named = true,
  },
  [sym_param_ty_list] = {
    .visible = true,
    .named = true,
  },
  [sym_task_body] = {
    .visible = true,
    .named = true,
  },
  [sym_global] = {
    .visible = true,
    .named = true,
  },
  [sym_struct] = {
    .visible = true,
    .named = true,
  },
  [sym_enum] = {
    .visible = true,
    .named = true,
  },
  [sym_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_call] = {
    .visible = true,
    .named = true,
  },
  [sym_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_let] = {
    .visible = true,
    .named = true,
  },
  [sym_uninit] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym_literal] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_param_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_param_ty_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_task_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_call_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_body = 1,
  field_name = 2,
  field_params = 3,
  field_returns = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_body] = "body",
  [field_name] = "name",
  [field_params] = "params",
  [field_returns] = "returns",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 3},
  [2] = {.index = 3, .length = 5},
  [3] = {.index = 8, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_body, 3},
    {field_name, 1},
    {field_params, 2},
  [3] =
    {field_body, 5},
    {field_name, 1},
    {field_params, 2},
    {field_returns, 3},
    {field_returns, 4},
  [8] =
    {field_name, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
  [124] = 124,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(61);
      ADVANCE_MAP(
        '"', 7,
        '&', 79,
        '(', 71,
        ')', 73,
        '*', 80,
        ',', 72,
        '-', 82,
        '/', 9,
        ':', 69,
        ';', 67,
        '=', 76,
        '[', 96,
        ']', 97,
        'b', 43,
        'e', 38,
        'g', 35,
        'i', 10,
        'l', 25,
        'r', 27,
        's', 19,
        't', 16,
        'u', 11,
        '{', 74,
        '}', 75,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(129);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(62);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(7);
      if (lookahead == '&') ADVANCE(79);
      if (lookahead == ')') ADVANCE(73);
      if (lookahead == '*') ADVANCE(80);
      if (lookahead == '-') ADVANCE(81);
      if (lookahead == ';') ADVANCE(67);
      if (lookahead == '}') ADVANCE(75);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(129);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(127);
      END_STATE();
    case 3:
      ADVANCE_MAP(
        '"', 7,
        '&', 79,
        '*', 80,
        '-', 81,
        'l', 105,
        'r', 108,
        's', 103,
        'u', 115,
        '}', 75,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(129);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(127);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(128);
      if (lookahead == '\\') ADVANCE(60);
      if (lookahead == 'u') ADVANCE(6);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(7);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(128);
      if (lookahead == '\\') ADVANCE(60);
      if (lookahead == 'u') ADVANCE(6);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(4);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 6:
      if (lookahead == '"') ADVANCE(128);
      if (lookahead == '\\') ADVANCE(60);
      if (lookahead == 'u') ADVANCE(6);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(5);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 7:
      if (lookahead == '"') ADVANCE(128);
      if (lookahead == '\\') ADVANCE(60);
      if (lookahead == 'u') ADVANCE(6);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 8:
      ADVANCE_MAP(
        '&', 79,
        ')', 73,
        ',', 72,
        '-', 15,
        ';', 67,
        '=', 76,
        '[', 96,
        'b', 119,
        't', 102,
        '{', 74,
        '}', 75,
        'i', 98,
        'u', 98,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(8);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(127);
      END_STATE();
    case 9:
      if (lookahead == '/') ADVANCE(1);
      END_STATE();
    case 10:
      if (lookahead == '1') ADVANCE(14);
      if (lookahead == '3') ADVANCE(12);
      if (lookahead == '6') ADVANCE(13);
      if (lookahead == '8') ADVANCE(94);
      END_STATE();
    case 11:
      if (lookahead == '1') ADVANCE(14);
      if (lookahead == '3') ADVANCE(12);
      if (lookahead == '6') ADVANCE(13);
      if (lookahead == '8') ADVANCE(94);
      if (lookahead == 'n') ADVANCE(30);
      if (lookahead == 's') ADVANCE(22);
      END_STATE();
    case 12:
      if (lookahead == '2') ADVANCE(94);
      END_STATE();
    case 13:
      if (lookahead == '4') ADVANCE(94);
      END_STATE();
    case 14:
      if (lookahead == '6') ADVANCE(94);
      END_STATE();
    case 15:
      if (lookahead == '>') ADVANCE(66);
      END_STATE();
    case 16:
      if (lookahead == 'a') ADVANCE(49);
      END_STATE();
    case 17:
      if (lookahead == 'a') ADVANCE(34);
      END_STATE();
    case 18:
      if (lookahead == 'b') ADVANCE(17);
      END_STATE();
    case 19:
      if (lookahead == 'c') ADVANCE(29);
      if (lookahead == 't') ADVANCE(47);
      END_STATE();
    case 20:
      if (lookahead == 'c') ADVANCE(51);
      END_STATE();
    case 21:
      if (lookahead == 'd') ADVANCE(57);
      END_STATE();
    case 22:
      if (lookahead == 'e') ADVANCE(70);
      END_STATE();
    case 23:
      if (lookahead == 'e') ADVANCE(21);
      END_STATE();
    case 24:
      if (lookahead == 'e') ADVANCE(85);
      END_STATE();
    case 25:
      if (lookahead == 'e') ADVANCE(50);
      END_STATE();
    case 26:
      if (lookahead == 'e') ADVANCE(45);
      END_STATE();
    case 27:
      if (lookahead == 'e') ADVANCE(53);
      END_STATE();
    case 28:
      if (lookahead == 'e') ADVANCE(46);
      END_STATE();
    case 29:
      if (lookahead == 'h') ADVANCE(23);
      END_STATE();
    case 30:
      if (lookahead == 'i') ADVANCE(41);
      END_STATE();
    case 31:
      if (lookahead == 'i') ADVANCE(52);
      END_STATE();
    case 32:
      if (lookahead == 'k') ADVANCE(64);
      END_STATE();
    case 33:
      if (lookahead == 'l') ADVANCE(92);
      END_STATE();
    case 34:
      if (lookahead == 'l') ADVANCE(68);
      END_STATE();
    case 35:
      if (lookahead == 'l') ADVANCE(42);
      END_STATE();
    case 36:
      if (lookahead == 'l') ADVANCE(24);
      END_STATE();
    case 37:
      if (lookahead == 'm') ADVANCE(78);
      END_STATE();
    case 38:
      if (lookahead == 'n') ADVANCE(55);
      if (lookahead == 'v') ADVANCE(26);
      if (lookahead == 'x') ADVANCE(54);
      END_STATE();
    case 39:
      if (lookahead == 'n') ADVANCE(63);
      END_STATE();
    case 40:
      if (lookahead == 'n') ADVANCE(83);
      END_STATE();
    case 41:
      if (lookahead == 'n') ADVANCE(31);
      END_STATE();
    case 42:
      if (lookahead == 'o') ADVANCE(18);
      END_STATE();
    case 43:
      if (lookahead == 'o') ADVANCE(44);
      END_STATE();
    case 44:
      if (lookahead == 'o') ADVANCE(33);
      END_STATE();
    case 45:
      if (lookahead == 'r') ADVANCE(59);
      END_STATE();
    case 46:
      if (lookahead == 'r') ADVANCE(39);
      END_STATE();
    case 47:
      if (lookahead == 'r') ADVANCE(56);
      END_STATE();
    case 48:
      if (lookahead == 'r') ADVANCE(40);
      END_STATE();
    case 49:
      if (lookahead == 's') ADVANCE(32);
      END_STATE();
    case 50:
      if (lookahead == 't') ADVANCE(88);
      END_STATE();
    case 51:
      if (lookahead == 't') ADVANCE(77);
      END_STATE();
    case 52:
      if (lookahead == 't') ADVANCE(90);
      END_STATE();
    case 53:
      if (lookahead == 't') ADVANCE(58);
      END_STATE();
    case 54:
      if (lookahead == 't') ADVANCE(28);
      END_STATE();
    case 55:
      if (lookahead == 'u') ADVANCE(37);
      END_STATE();
    case 56:
      if (lookahead == 'u') ADVANCE(20);
      END_STATE();
    case 57:
      if (lookahead == 'u') ADVANCE(36);
      END_STATE();
    case 58:
      if (lookahead == 'u') ADVANCE(48);
      END_STATE();
    case 59:
      if (lookahead == 'y') ADVANCE(87);
      END_STATE();
    case 60:
      if (lookahead == '"' ||
          lookahead == '\\' ||
          lookahead == 'b' ||
          lookahead == 'f' ||
          lookahead == 'n' ||
          lookahead == 'r' ||
          lookahead == 't') ADVANCE(7);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_line_comment);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_extern);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_task);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_task);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(127);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_global);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_use);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_struct);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_enum);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_AMP);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '>') ADVANCE(66);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_return);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_return);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(127);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_schedule);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_schedule);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(127);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_every);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_let);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(127);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_uninit);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_uninit);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(127);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_bool);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(anon_sym_bool);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(127);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(aux_sym_type_token1);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(aux_sym_type_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(127);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '1') ADVANCE(101);
      if (lookahead == '3') ADVANCE(99);
      if (lookahead == '6') ADVANCE(100);
      if (lookahead == '8') ADVANCE(95);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(127);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '2') ADVANCE(95);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(127);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '4') ADVANCE(95);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(127);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '6') ADVANCE(95);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(127);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'a') ADVANCE(121);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(127);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'c') ADVANCE(109);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(127);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'd') ADVANCE(126);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(127);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'e') ADVANCE(122);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(127);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'e') ADVANCE(104);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(127);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'e') ADVANCE(86);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(127);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'e') ADVANCE(123);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(127);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'h') ADVANCE(106);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(127);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'i') ADVANCE(124);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(127);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'i') ADVANCE(117);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(127);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'k') ADVANCE(65);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(127);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'l') ADVANCE(93);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(127);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'l') ADVANCE(107);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(127);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'n') ADVANCE(111);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(127);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'n') ADVANCE(84);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(127);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'n') ADVANCE(110);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(127);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'o') ADVANCE(113);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(127);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'o') ADVANCE(118);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(127);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'r') ADVANCE(116);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(127);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 's') ADVANCE(112);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(127);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 't') ADVANCE(89);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(127);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 't') ADVANCE(125);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(127);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 't') ADVANCE(91);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(127);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'u') ADVANCE(120);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(127);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'u') ADVANCE(114);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(127);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(sym_ident);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(127);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(sym_int);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(129);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 3},
  [3] = {.lex_state = 3},
  [4] = {.lex_state = 3},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 3},
  [8] = {.lex_state = 3},
  [9] = {.lex_state = 3},
  [10] = {.lex_state = 3},
  [11] = {.lex_state = 3},
  [12] = {.lex_state = 3},
  [13] = {.lex_state = 2},
  [14] = {.lex_state = 2},
  [15] = {.lex_state = 2},
  [16] = {.lex_state = 2},
  [17] = {.lex_state = 2},
  [18] = {.lex_state = 2},
  [19] = {.lex_state = 2},
  [20] = {.lex_state = 2},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 8},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 8},
  [36] = {.lex_state = 8},
  [37] = {.lex_state = 8},
  [38] = {.lex_state = 8},
  [39] = {.lex_state = 8},
  [40] = {.lex_state = 8},
  [41] = {.lex_state = 8},
  [42] = {.lex_state = 8},
  [43] = {.lex_state = 8},
  [44] = {.lex_state = 8},
  [45] = {.lex_state = 8},
  [46] = {.lex_state = 8},
  [47] = {.lex_state = 8},
  [48] = {.lex_state = 8},
  [49] = {.lex_state = 8},
  [50] = {.lex_state = 8},
  [51] = {.lex_state = 8},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 8},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 8},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 8},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 8},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 2},
  [84] = {.lex_state = 2},
  [85] = {.lex_state = 8},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 2},
  [90] = {.lex_state = 2},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 2},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 2},
  [98] = {.lex_state = 2},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 2},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 2},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 2},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 2},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 2},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_line_comment] = ACTIONS(1),
    [anon_sym_extern] = ACTIONS(1),
    [anon_sym_task] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_global] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_use] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_struct] = ACTIONS(1),
    [anon_sym_enum] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_return] = ACTIONS(1),
    [anon_sym_schedule] = ACTIONS(1),
    [anon_sym_every] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_uninit] = ACTIONS(1),
    [anon_sym_bool] = ACTIONS(1),
    [aux_sym_type_token1] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_int] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(119),
    [sym__decl] = STATE(6),
    [sym_extern_task] = STATE(6),
    [sym_extern_global] = STATE(6),
    [sym_use] = STATE(6),
    [sym_task] = STATE(6),
    [sym_global] = STATE(6),
    [sym_struct] = STATE(6),
    [sym_enum] = STATE(6),
    [aux_sym_source_file_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_line_comment] = ACTIONS(5),
    [anon_sym_extern] = ACTIONS(7),
    [anon_sym_task] = ACTIONS(9),
    [anon_sym_global] = ACTIONS(11),
    [anon_sym_use] = ACTIONS(13),
    [anon_sym_struct] = ACTIONS(15),
    [anon_sym_enum] = ACTIONS(17),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(19), 1,
      anon_sym_RBRACE,
    ACTIONS(23), 1,
      anon_sym_return,
    ACTIONS(25), 1,
      anon_sym_schedule,
    ACTIONS(27), 1,
      anon_sym_let,
    ACTIONS(29), 1,
      anon_sym_uninit,
    ACTIONS(31), 1,
      sym_ident,
    STATE(107), 1,
      sym_expr,
    ACTIONS(33), 2,
      sym_string,
      sym_int,
    STATE(4), 2,
      sym_stmt,
      aux_sym_task_body_repeat1,
    STATE(8), 2,
      sym_let,
      sym_uninit,
    STATE(59), 2,
      sym_call,
      sym_literal,
    ACTIONS(21), 3,
      anon_sym_AMP,
      anon_sym_STAR,
      anon_sym_DASH,
  [43] = 12,
    ACTIONS(35), 1,
      anon_sym_RBRACE,
    ACTIONS(40), 1,
      anon_sym_return,
    ACTIONS(43), 1,
      anon_sym_schedule,
    ACTIONS(46), 1,
      anon_sym_let,
    ACTIONS(49), 1,
      anon_sym_uninit,
    ACTIONS(52), 1,
      sym_ident,
    STATE(107), 1,
      sym_expr,
    ACTIONS(55), 2,
      sym_string,
      sym_int,
    STATE(3), 2,
      sym_stmt,
      aux_sym_task_body_repeat1,
    STATE(8), 2,
      sym_let,
      sym_uninit,
    STATE(59), 2,
      sym_call,
      sym_literal,
    ACTIONS(37), 3,
      anon_sym_AMP,
      anon_sym_STAR,
      anon_sym_DASH,
  [86] = 12,
    ACTIONS(23), 1,
      anon_sym_return,
    ACTIONS(25), 1,
      anon_sym_schedule,
    ACTIONS(27), 1,
      anon_sym_let,
    ACTIONS(29), 1,
      anon_sym_uninit,
    ACTIONS(31), 1,
      sym_ident,
    ACTIONS(58), 1,
      anon_sym_RBRACE,
    STATE(107), 1,
      sym_expr,
    ACTIONS(33), 2,
      sym_string,
      sym_int,
    STATE(3), 2,
      sym_stmt,
      aux_sym_task_body_repeat1,
    STATE(8), 2,
      sym_let,
      sym_uninit,
    STATE(59), 2,
      sym_call,
      sym_literal,
    ACTIONS(21), 3,
      anon_sym_AMP,
      anon_sym_STAR,
      anon_sym_DASH,
  [129] = 9,
    ACTIONS(60), 1,
      ts_builtin_sym_end,
    ACTIONS(62), 1,
      sym_line_comment,
    ACTIONS(65), 1,
      anon_sym_extern,
    ACTIONS(68), 1,
      anon_sym_task,
    ACTIONS(71), 1,
      anon_sym_global,
    ACTIONS(74), 1,
      anon_sym_use,
    ACTIONS(77), 1,
      anon_sym_struct,
    ACTIONS(80), 1,
      anon_sym_enum,
    STATE(5), 9,
      sym__decl,
      sym_extern_task,
      sym_extern_global,
      sym_use,
      sym_task,
      sym_global,
      sym_struct,
      sym_enum,
      aux_sym_source_file_repeat1,
  [165] = 9,
    ACTIONS(7), 1,
      anon_sym_extern,
    ACTIONS(9), 1,
      anon_sym_task,
    ACTIONS(11), 1,
      anon_sym_global,
    ACTIONS(13), 1,
      anon_sym_use,
    ACTIONS(15), 1,
      anon_sym_struct,
    ACTIONS(17), 1,
      anon_sym_enum,
    ACTIONS(83), 1,
      ts_builtin_sym_end,
    ACTIONS(85), 1,
      sym_line_comment,
    STATE(5), 9,
      sym__decl,
      sym_extern_task,
      sym_extern_global,
      sym_use,
      sym_task,
      sym_global,
      sym_struct,
      sym_enum,
      aux_sym_source_file_repeat1,
  [201] = 2,
    ACTIONS(89), 5,
      anon_sym_return,
      anon_sym_schedule,
      anon_sym_let,
      anon_sym_uninit,
      sym_ident,
    ACTIONS(87), 6,
      anon_sym_RBRACE,
      anon_sym_AMP,
      anon_sym_STAR,
      anon_sym_DASH,
      sym_string,
      sym_int,
  [217] = 2,
    ACTIONS(93), 5,
      anon_sym_return,
      anon_sym_schedule,
      anon_sym_let,
      anon_sym_uninit,
      sym_ident,
    ACTIONS(91), 6,
      anon_sym_RBRACE,
      anon_sym_AMP,
      anon_sym_STAR,
      anon_sym_DASH,
      sym_string,
      sym_int,
  [233] = 2,
    ACTIONS(97), 5,
      anon_sym_return,
      anon_sym_schedule,
      anon_sym_let,
      anon_sym_uninit,
      sym_ident,
    ACTIONS(95), 6,
      anon_sym_RBRACE,
      anon_sym_AMP,
      anon_sym_STAR,
      anon_sym_DASH,
      sym_string,
      sym_int,
  [249] = 2,
    ACTIONS(101), 5,
      anon_sym_return,
      anon_sym_schedule,
      anon_sym_let,
      anon_sym_uninit,
      sym_ident,
    ACTIONS(99), 6,
      anon_sym_RBRACE,
      anon_sym_AMP,
      anon_sym_STAR,
      anon_sym_DASH,
      sym_string,
      sym_int,
  [265] = 2,
    ACTIONS(105), 5,
      anon_sym_return,
      anon_sym_schedule,
      anon_sym_let,
      anon_sym_uninit,
      sym_ident,
    ACTIONS(103), 6,
      anon_sym_RBRACE,
      anon_sym_AMP,
      anon_sym_STAR,
      anon_sym_DASH,
      sym_string,
      sym_int,
  [281] = 2,
    ACTIONS(109), 5,
      anon_sym_return,
      anon_sym_schedule,
      anon_sym_let,
      anon_sym_uninit,
      sym_ident,
    ACTIONS(107), 6,
      anon_sym_RBRACE,
      anon_sym_AMP,
      anon_sym_STAR,
      anon_sym_DASH,
      sym_string,
      sym_int,
  [297] = 6,
    ACTIONS(111), 1,
      anon_sym_SEMI,
    ACTIONS(113), 1,
      sym_ident,
    STATE(109), 1,
      sym_expr,
    ACTIONS(33), 2,
      sym_string,
      sym_int,
    STATE(59), 2,
      sym_call,
      sym_literal,
    ACTIONS(21), 3,
      anon_sym_AMP,
      anon_sym_STAR,
      anon_sym_DASH,
  [320] = 6,
    ACTIONS(113), 1,
      sym_ident,
    ACTIONS(115), 1,
      anon_sym_RPAREN,
    STATE(70), 1,
      sym_expr,
    ACTIONS(33), 2,
      sym_string,
      sym_int,
    STATE(59), 2,
      sym_call,
      sym_literal,
    ACTIONS(21), 3,
      anon_sym_AMP,
      anon_sym_STAR,
      anon_sym_DASH,
  [343] = 5,
    ACTIONS(113), 1,
      sym_ident,
    STATE(122), 1,
      sym_expr,
    ACTIONS(33), 2,
      sym_string,
      sym_int,
    STATE(59), 2,
      sym_call,
      sym_literal,
    ACTIONS(21), 3,
      anon_sym_AMP,
      anon_sym_STAR,
      anon_sym_DASH,
  [363] = 5,
    ACTIONS(113), 1,
      sym_ident,
    STATE(113), 1,
      sym_expr,
    ACTIONS(33), 2,
      sym_string,
      sym_int,
    STATE(59), 2,
      sym_call,
      sym_literal,
    ACTIONS(21), 3,
      anon_sym_AMP,
      anon_sym_STAR,
      anon_sym_DASH,
  [383] = 5,
    ACTIONS(113), 1,
      sym_ident,
    STATE(60), 1,
      sym_expr,
    ACTIONS(33), 2,
      sym_string,
      sym_int,
    STATE(59), 2,
      sym_call,
      sym_literal,
    ACTIONS(21), 3,
      anon_sym_AMP,
      anon_sym_STAR,
      anon_sym_DASH,
  [403] = 5,
    ACTIONS(113), 1,
      sym_ident,
    STATE(108), 1,
      sym_expr,
    ACTIONS(33), 2,
      sym_string,
      sym_int,
    STATE(59), 2,
      sym_call,
      sym_literal,
    ACTIONS(21), 3,
      anon_sym_AMP,
      anon_sym_STAR,
      anon_sym_DASH,
  [423] = 5,
    ACTIONS(113), 1,
      sym_ident,
    STATE(103), 1,
      sym_expr,
    ACTIONS(33), 2,
      sym_string,
      sym_int,
    STATE(59), 2,
      sym_call,
      sym_literal,
    ACTIONS(21), 3,
      anon_sym_AMP,
      anon_sym_STAR,
      anon_sym_DASH,
  [443] = 5,
    ACTIONS(113), 1,
      sym_ident,
    STATE(88), 1,
      sym_expr,
    ACTIONS(33), 2,
      sym_string,
      sym_int,
    STATE(59), 2,
      sym_call,
      sym_literal,
    ACTIONS(21), 3,
      anon_sym_AMP,
      anon_sym_STAR,
      anon_sym_DASH,
  [463] = 1,
    ACTIONS(117), 8,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_extern,
      anon_sym_task,
      anon_sym_global,
      anon_sym_use,
      anon_sym_struct,
      anon_sym_enum,
  [474] = 6,
    ACTIONS(119), 1,
      anon_sym_task,
    ACTIONS(121), 1,
      anon_sym_RPAREN,
    ACTIONS(123), 1,
      anon_sym_AMP,
    ACTIONS(127), 1,
      anon_sym_LBRACK,
    STATE(66), 1,
      sym_type,
    ACTIONS(125), 3,
      anon_sym_bool,
      aux_sym_type_token1,
      sym_ident,
  [495] = 1,
    ACTIONS(129), 8,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_extern,
      anon_sym_task,
      anon_sym_global,
      anon_sym_use,
      anon_sym_struct,
      anon_sym_enum,
  [506] = 1,
    ACTIONS(131), 8,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_extern,
      anon_sym_task,
      anon_sym_global,
      anon_sym_use,
      anon_sym_struct,
      anon_sym_enum,
  [517] = 1,
    ACTIONS(133), 8,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_extern,
      anon_sym_task,
      anon_sym_global,
      anon_sym_use,
      anon_sym_struct,
      anon_sym_enum,
  [528] = 1,
    ACTIONS(135), 8,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_extern,
      anon_sym_task,
      anon_sym_global,
      anon_sym_use,
      anon_sym_struct,
      anon_sym_enum,
  [539] = 1,
    ACTIONS(137), 8,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_extern,
      anon_sym_task,
      anon_sym_global,
      anon_sym_use,
      anon_sym_struct,
      anon_sym_enum,
  [550] = 1,
    ACTIONS(139), 8,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_extern,
      anon_sym_task,
      anon_sym_global,
      anon_sym_use,
      anon_sym_struct,
      anon_sym_enum,
  [561] = 1,
    ACTIONS(141), 8,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_extern,
      anon_sym_task,
      anon_sym_global,
      anon_sym_use,
      anon_sym_struct,
      anon_sym_enum,
  [572] = 1,
    ACTIONS(143), 8,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_extern,
      anon_sym_task,
      anon_sym_global,
      anon_sym_use,
      anon_sym_struct,
      anon_sym_enum,
  [583] = 1,
    ACTIONS(145), 8,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_extern,
      anon_sym_task,
      anon_sym_global,
      anon_sym_use,
      anon_sym_struct,
      anon_sym_enum,
  [594] = 1,
    ACTIONS(147), 8,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_extern,
      anon_sym_task,
      anon_sym_global,
      anon_sym_use,
      anon_sym_struct,
      anon_sym_enum,
  [605] = 1,
    ACTIONS(149), 8,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_extern,
      anon_sym_task,
      anon_sym_global,
      anon_sym_use,
      anon_sym_struct,
      anon_sym_enum,
  [616] = 1,
    ACTIONS(151), 8,
      ts_builtin_sym_end,
      sym_line_comment,
      anon_sym_extern,
      anon_sym_task,
      anon_sym_global,
      anon_sym_use,
      anon_sym_struct,
      anon_sym_enum,
  [627] = 5,
    ACTIONS(119), 1,
      anon_sym_task,
    ACTIONS(123), 1,
      anon_sym_AMP,
    ACTIONS(127), 1,
      anon_sym_LBRACK,
    STATE(78), 1,
      sym_type,
    ACTIONS(125), 3,
      anon_sym_bool,
      aux_sym_type_token1,
      sym_ident,
  [645] = 2,
    ACTIONS(153), 1,
      anon_sym_DASH_GT,
    ACTIONS(155), 6,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
  [657] = 5,
    ACTIONS(119), 1,
      anon_sym_task,
    ACTIONS(123), 1,
      anon_sym_AMP,
    ACTIONS(127), 1,
      anon_sym_LBRACK,
    STATE(53), 1,
      sym_type,
    ACTIONS(125), 3,
      anon_sym_bool,
      aux_sym_type_token1,
      sym_ident,
  [675] = 1,
    ACTIONS(157), 7,
      anon_sym_DASH_GT,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
  [685] = 5,
    ACTIONS(119), 1,
      anon_sym_task,
    ACTIONS(123), 1,
      anon_sym_AMP,
    ACTIONS(127), 1,
      anon_sym_LBRACK,
    STATE(52), 1,
      sym_type,
    ACTIONS(125), 3,
      anon_sym_bool,
      aux_sym_type_token1,
      sym_ident,
  [703] = 5,
    ACTIONS(119), 1,
      anon_sym_task,
    ACTIONS(123), 1,
      anon_sym_AMP,
    ACTIONS(127), 1,
      anon_sym_LBRACK,
    STATE(124), 1,
      sym_type,
    ACTIONS(125), 3,
      anon_sym_bool,
      aux_sym_type_token1,
      sym_ident,
  [721] = 1,
    ACTIONS(159), 7,
      anon_sym_DASH_GT,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
  [731] = 5,
    ACTIONS(119), 1,
      anon_sym_task,
    ACTIONS(123), 1,
      anon_sym_AMP,
    ACTIONS(127), 1,
      anon_sym_LBRACK,
    STATE(87), 1,
      sym_type,
    ACTIONS(125), 3,
      anon_sym_bool,
      aux_sym_type_token1,
      sym_ident,
  [749] = 5,
    ACTIONS(119), 1,
      anon_sym_task,
    ACTIONS(123), 1,
      anon_sym_AMP,
    ACTIONS(127), 1,
      anon_sym_LBRACK,
    STATE(104), 1,
      sym_type,
    ACTIONS(125), 3,
      anon_sym_bool,
      aux_sym_type_token1,
      sym_ident,
  [767] = 5,
    ACTIONS(119), 1,
      anon_sym_task,
    ACTIONS(123), 1,
      anon_sym_AMP,
    ACTIONS(127), 1,
      anon_sym_LBRACK,
    STATE(69), 1,
      sym_type,
    ACTIONS(125), 3,
      anon_sym_bool,
      aux_sym_type_token1,
      sym_ident,
  [785] = 5,
    ACTIONS(119), 1,
      anon_sym_task,
    ACTIONS(123), 1,
      anon_sym_AMP,
    ACTIONS(127), 1,
      anon_sym_LBRACK,
    STATE(91), 1,
      sym_type,
    ACTIONS(125), 3,
      anon_sym_bool,
      aux_sym_type_token1,
      sym_ident,
  [803] = 5,
    ACTIONS(119), 1,
      anon_sym_task,
    ACTIONS(123), 1,
      anon_sym_AMP,
    ACTIONS(127), 1,
      anon_sym_LBRACK,
    STATE(120), 1,
      sym_type,
    ACTIONS(125), 3,
      anon_sym_bool,
      aux_sym_type_token1,
      sym_ident,
  [821] = 5,
    ACTIONS(119), 1,
      anon_sym_task,
    ACTIONS(123), 1,
      anon_sym_AMP,
    ACTIONS(127), 1,
      anon_sym_LBRACK,
    STATE(65), 1,
      sym_type,
    ACTIONS(125), 3,
      anon_sym_bool,
      aux_sym_type_token1,
      sym_ident,
  [839] = 5,
    ACTIONS(119), 1,
      anon_sym_task,
    ACTIONS(123), 1,
      anon_sym_AMP,
    ACTIONS(127), 1,
      anon_sym_LBRACK,
    STATE(116), 1,
      sym_type,
    ACTIONS(125), 3,
      anon_sym_bool,
      aux_sym_type_token1,
      sym_ident,
  [857] = 1,
    ACTIONS(161), 7,
      anon_sym_DASH_GT,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
  [867] = 5,
    ACTIONS(119), 1,
      anon_sym_task,
    ACTIONS(123), 1,
      anon_sym_AMP,
    ACTIONS(127), 1,
      anon_sym_LBRACK,
    STATE(123), 1,
      sym_type,
    ACTIONS(125), 3,
      anon_sym_bool,
      aux_sym_type_token1,
      sym_ident,
  [885] = 5,
    ACTIONS(119), 1,
      anon_sym_task,
    ACTIONS(123), 1,
      anon_sym_AMP,
    ACTIONS(127), 1,
      anon_sym_LBRACK,
    STATE(81), 1,
      sym_type,
    ACTIONS(125), 3,
      anon_sym_bool,
      aux_sym_type_token1,
      sym_ident,
  [903] = 1,
    ACTIONS(163), 6,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
  [912] = 1,
    ACTIONS(155), 6,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
  [921] = 1,
    ACTIONS(165), 6,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
  [930] = 1,
    ACTIONS(167), 6,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
  [939] = 2,
    ACTIONS(171), 1,
      anon_sym_LPAREN,
    ACTIONS(169), 4,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_every,
  [949] = 1,
    ACTIONS(173), 4,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_every,
  [956] = 1,
    ACTIONS(175), 4,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_every,
  [963] = 1,
    ACTIONS(169), 4,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_every,
  [970] = 1,
    ACTIONS(177), 4,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_every,
  [977] = 3,
    ACTIONS(179), 1,
      anon_sym_COMMA,
    STATE(61), 1,
      aux_sym_param_list_repeat1,
    ACTIONS(182), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [988] = 1,
    ACTIONS(184), 4,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_every,
  [995] = 1,
    ACTIONS(186), 4,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_every,
  [1002] = 3,
    ACTIONS(188), 1,
      anon_sym_COMMA,
    ACTIONS(190), 1,
      anon_sym_RPAREN,
    STATE(77), 1,
      aux_sym_call_repeat1,
  [1012] = 3,
    ACTIONS(192), 1,
      anon_sym_COMMA,
    ACTIONS(194), 1,
      anon_sym_RPAREN,
    STATE(68), 1,
      aux_sym_param_list_repeat1,
  [1022] = 3,
    ACTIONS(196), 1,
      anon_sym_COMMA,
    ACTIONS(198), 1,
      anon_sym_RPAREN,
    STATE(71), 1,
      aux_sym_param_ty_list_repeat1,
  [1032] = 1,
    ACTIONS(200), 3,
      anon_sym_DASH_GT,
      anon_sym_SEMI,
      anon_sym_LBRACE,
  [1038] = 3,
    ACTIONS(192), 1,
      anon_sym_COMMA,
    ACTIONS(202), 1,
      anon_sym_RPAREN,
    STATE(61), 1,
      aux_sym_param_list_repeat1,
  [1048] = 3,
    ACTIONS(192), 1,
      anon_sym_COMMA,
    ACTIONS(204), 1,
      anon_sym_RBRACE,
    STATE(73), 1,
      aux_sym_param_list_repeat1,
  [1058] = 3,
    ACTIONS(188), 1,
      anon_sym_COMMA,
    ACTIONS(206), 1,
      anon_sym_RPAREN,
    STATE(64), 1,
      aux_sym_call_repeat1,
  [1068] = 3,
    ACTIONS(196), 1,
      anon_sym_COMMA,
    ACTIONS(208), 1,
      anon_sym_RPAREN,
    STATE(75), 1,
      aux_sym_param_ty_list_repeat1,
  [1078] = 3,
    ACTIONS(210), 1,
      anon_sym_DASH_GT,
    ACTIONS(212), 1,
      anon_sym_LBRACE,
    STATE(26), 1,
      sym_task_body,
  [1088] = 3,
    ACTIONS(192), 1,
      anon_sym_COMMA,
    ACTIONS(214), 1,
      anon_sym_RBRACE,
    STATE(61), 1,
      aux_sym_param_list_repeat1,
  [1098] = 1,
    ACTIONS(216), 3,
      anon_sym_DASH_GT,
      anon_sym_SEMI,
      anon_sym_LBRACE,
  [1104] = 3,
    ACTIONS(218), 1,
      anon_sym_COMMA,
    ACTIONS(221), 1,
      anon_sym_RPAREN,
    STATE(75), 1,
      aux_sym_param_ty_list_repeat1,
  [1114] = 1,
    ACTIONS(223), 3,
      anon_sym_DASH_GT,
      anon_sym_SEMI,
      anon_sym_LBRACE,
  [1120] = 3,
    ACTIONS(225), 1,
      anon_sym_COMMA,
    ACTIONS(228), 1,
      anon_sym_RPAREN,
    STATE(77), 1,
      aux_sym_call_repeat1,
  [1130] = 1,
    ACTIONS(230), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [1136] = 2,
    ACTIONS(232), 1,
      anon_sym_LPAREN,
    STATE(36), 1,
      sym_param_ty_list,
  [1143] = 2,
    ACTIONS(234), 1,
      anon_sym_LPAREN,
    STATE(72), 1,
      sym_param_list,
  [1150] = 2,
    ACTIONS(212), 1,
      anon_sym_LBRACE,
    STATE(25), 1,
      sym_task_body,
  [1157] = 2,
    ACTIONS(234), 1,
      anon_sym_LPAREN,
    STATE(85), 1,
      sym_param_list,
  [1164] = 2,
    ACTIONS(236), 1,
      anon_sym_RPAREN,
    ACTIONS(238), 1,
      sym_ident,
  [1171] = 2,
    ACTIONS(240), 1,
      anon_sym_RBRACE,
    ACTIONS(242), 1,
      sym_ident,
  [1178] = 2,
    ACTIONS(244), 1,
      anon_sym_DASH_GT,
    ACTIONS(246), 1,
      anon_sym_SEMI,
  [1185] = 2,
    ACTIONS(248), 1,
      anon_sym_task,
    ACTIONS(250), 1,
      anon_sym_global,
  [1192] = 1,
    ACTIONS(221), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1197] = 1,
    ACTIONS(228), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1202] = 1,
    ACTIONS(252), 1,
      sym_ident,
  [1206] = 1,
    ACTIONS(254), 1,
      sym_ident,
  [1210] = 1,
    ACTIONS(256), 1,
      anon_sym_EQ,
  [1214] = 1,
    ACTIONS(258), 1,
      anon_sym_COLON,
  [1218] = 1,
    ACTIONS(260), 1,
      anon_sym_COLON,
  [1222] = 1,
    ACTIONS(262), 1,
      anon_sym_COLON,
  [1226] = 1,
    ACTIONS(264), 1,
      sym_ident,
  [1230] = 1,
    ACTIONS(266), 1,
      anon_sym_RBRACK,
  [1234] = 1,
    ACTIONS(268), 1,
      sym_ident,
  [1238] = 1,
    ACTIONS(270), 1,
      sym_ident,
  [1242] = 1,
    ACTIONS(272), 1,
      anon_sym_SEMI,
  [1246] = 1,
    ACTIONS(274), 1,
      anon_sym_COLON,
  [1250] = 1,
    ACTIONS(276), 1,
      sym_int,
  [1254] = 1,
    ACTIONS(278), 1,
      sym_ident,
  [1258] = 1,
    ACTIONS(280), 1,
      anon_sym_SEMI,
  [1262] = 1,
    ACTIONS(282), 1,
      anon_sym_EQ,
  [1266] = 1,
    ACTIONS(284), 1,
      anon_sym_COLON,
  [1270] = 1,
    ACTIONS(286), 1,
      sym_ident,
  [1274] = 1,
    ACTIONS(111), 1,
      anon_sym_SEMI,
  [1278] = 1,
    ACTIONS(288), 1,
      anon_sym_SEMI,
  [1282] = 1,
    ACTIONS(290), 1,
      anon_sym_SEMI,
  [1286] = 1,
    ACTIONS(292), 1,
      anon_sym_RBRACE,
  [1290] = 1,
    ACTIONS(294), 1,
      anon_sym_LBRACE,
  [1294] = 1,
    ACTIONS(296), 1,
      sym_ident,
  [1298] = 1,
    ACTIONS(298), 1,
      anon_sym_every,
  [1302] = 1,
    ACTIONS(300), 1,
      anon_sym_COLON,
  [1306] = 1,
    ACTIONS(302), 1,
      anon_sym_COLON,
  [1310] = 1,
    ACTIONS(304), 1,
      anon_sym_SEMI,
  [1314] = 1,
    ACTIONS(306), 1,
      sym_ident,
  [1318] = 1,
    ACTIONS(308), 1,
      anon_sym_LBRACE,
  [1322] = 1,
    ACTIONS(310), 1,
      ts_builtin_sym_end,
  [1326] = 1,
    ACTIONS(312), 1,
      anon_sym_SEMI,
  [1330] = 1,
    ACTIONS(314), 1,
      sym_ident,
  [1334] = 1,
    ACTIONS(316), 1,
      anon_sym_SEMI,
  [1338] = 1,
    ACTIONS(318), 1,
      anon_sym_SEMI,
  [1342] = 1,
    ACTIONS(320), 1,
      anon_sym_SEMI,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 43,
  [SMALL_STATE(4)] = 86,
  [SMALL_STATE(5)] = 129,
  [SMALL_STATE(6)] = 165,
  [SMALL_STATE(7)] = 201,
  [SMALL_STATE(8)] = 217,
  [SMALL_STATE(9)] = 233,
  [SMALL_STATE(10)] = 249,
  [SMALL_STATE(11)] = 265,
  [SMALL_STATE(12)] = 281,
  [SMALL_STATE(13)] = 297,
  [SMALL_STATE(14)] = 320,
  [SMALL_STATE(15)] = 343,
  [SMALL_STATE(16)] = 363,
  [SMALL_STATE(17)] = 383,
  [SMALL_STATE(18)] = 403,
  [SMALL_STATE(19)] = 423,
  [SMALL_STATE(20)] = 443,
  [SMALL_STATE(21)] = 463,
  [SMALL_STATE(22)] = 474,
  [SMALL_STATE(23)] = 495,
  [SMALL_STATE(24)] = 506,
  [SMALL_STATE(25)] = 517,
  [SMALL_STATE(26)] = 528,
  [SMALL_STATE(27)] = 539,
  [SMALL_STATE(28)] = 550,
  [SMALL_STATE(29)] = 561,
  [SMALL_STATE(30)] = 572,
  [SMALL_STATE(31)] = 583,
  [SMALL_STATE(32)] = 594,
  [SMALL_STATE(33)] = 605,
  [SMALL_STATE(34)] = 616,
  [SMALL_STATE(35)] = 627,
  [SMALL_STATE(36)] = 645,
  [SMALL_STATE(37)] = 657,
  [SMALL_STATE(38)] = 675,
  [SMALL_STATE(39)] = 685,
  [SMALL_STATE(40)] = 703,
  [SMALL_STATE(41)] = 721,
  [SMALL_STATE(42)] = 731,
  [SMALL_STATE(43)] = 749,
  [SMALL_STATE(44)] = 767,
  [SMALL_STATE(45)] = 785,
  [SMALL_STATE(46)] = 803,
  [SMALL_STATE(47)] = 821,
  [SMALL_STATE(48)] = 839,
  [SMALL_STATE(49)] = 857,
  [SMALL_STATE(50)] = 867,
  [SMALL_STATE(51)] = 885,
  [SMALL_STATE(52)] = 903,
  [SMALL_STATE(53)] = 912,
  [SMALL_STATE(54)] = 921,
  [SMALL_STATE(55)] = 930,
  [SMALL_STATE(56)] = 939,
  [SMALL_STATE(57)] = 949,
  [SMALL_STATE(58)] = 956,
  [SMALL_STATE(59)] = 963,
  [SMALL_STATE(60)] = 970,
  [SMALL_STATE(61)] = 977,
  [SMALL_STATE(62)] = 988,
  [SMALL_STATE(63)] = 995,
  [SMALL_STATE(64)] = 1002,
  [SMALL_STATE(65)] = 1012,
  [SMALL_STATE(66)] = 1022,
  [SMALL_STATE(67)] = 1032,
  [SMALL_STATE(68)] = 1038,
  [SMALL_STATE(69)] = 1048,
  [SMALL_STATE(70)] = 1058,
  [SMALL_STATE(71)] = 1068,
  [SMALL_STATE(72)] = 1078,
  [SMALL_STATE(73)] = 1088,
  [SMALL_STATE(74)] = 1098,
  [SMALL_STATE(75)] = 1104,
  [SMALL_STATE(76)] = 1114,
  [SMALL_STATE(77)] = 1120,
  [SMALL_STATE(78)] = 1130,
  [SMALL_STATE(79)] = 1136,
  [SMALL_STATE(80)] = 1143,
  [SMALL_STATE(81)] = 1150,
  [SMALL_STATE(82)] = 1157,
  [SMALL_STATE(83)] = 1164,
  [SMALL_STATE(84)] = 1171,
  [SMALL_STATE(85)] = 1178,
  [SMALL_STATE(86)] = 1185,
  [SMALL_STATE(87)] = 1192,
  [SMALL_STATE(88)] = 1197,
  [SMALL_STATE(89)] = 1202,
  [SMALL_STATE(90)] = 1206,
  [SMALL_STATE(91)] = 1210,
  [SMALL_STATE(92)] = 1214,
  [SMALL_STATE(93)] = 1218,
  [SMALL_STATE(94)] = 1222,
  [SMALL_STATE(95)] = 1226,
  [SMALL_STATE(96)] = 1230,
  [SMALL_STATE(97)] = 1234,
  [SMALL_STATE(98)] = 1238,
  [SMALL_STATE(99)] = 1242,
  [SMALL_STATE(100)] = 1246,
  [SMALL_STATE(101)] = 1250,
  [SMALL_STATE(102)] = 1254,
  [SMALL_STATE(103)] = 1258,
  [SMALL_STATE(104)] = 1262,
  [SMALL_STATE(105)] = 1266,
  [SMALL_STATE(106)] = 1270,
  [SMALL_STATE(107)] = 1274,
  [SMALL_STATE(108)] = 1278,
  [SMALL_STATE(109)] = 1282,
  [SMALL_STATE(110)] = 1286,
  [SMALL_STATE(111)] = 1290,
  [SMALL_STATE(112)] = 1294,
  [SMALL_STATE(113)] = 1298,
  [SMALL_STATE(114)] = 1302,
  [SMALL_STATE(115)] = 1306,
  [SMALL_STATE(116)] = 1310,
  [SMALL_STATE(117)] = 1314,
  [SMALL_STATE(118)] = 1318,
  [SMALL_STATE(119)] = 1322,
  [SMALL_STATE(120)] = 1326,
  [SMALL_STATE(121)] = 1330,
  [SMALL_STATE(122)] = 1334,
  [SMALL_STATE(123)] = 1338,
  [SMALL_STATE(124)] = 1342,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(97),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(98),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_task_body_repeat1, 2, 0, 0),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_task_body_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [40] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_task_body_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_task_body_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [46] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_task_body_repeat1, 2, 0, 0), SHIFT_REPEAT(97),
  [49] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_task_body_repeat1, 2, 0, 0), SHIFT_REPEAT(98),
  [52] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_task_body_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_task_body_repeat1, 2, 0, 0), SHIFT_REPEAT(58),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [62] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [65] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(86),
  [68] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(121),
  [71] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(102),
  [74] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(106),
  [77] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(89),
  [80] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(117),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_stmt, 3, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_stmt, 3, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_stmt, 1, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_stmt, 1, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_stmt, 2, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_stmt, 2, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_stmt, 5, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_stmt, 5, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_uninit, 5, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_uninit, 5, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let, 7, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_let, 7, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_task_body, 2, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = false}}, SHIFT(79),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [125] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_use, 3, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extern_global, 6, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_task, 6, 0, 2),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_task, 4, 0, 1),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_task_body, 3, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_global, 7, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extern_task, 7, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 7, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 8, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 4, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum, 4, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extern_task, 5, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 2, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_ty_list, 2, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_ty_list, 3, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_ty_list, 4, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 4, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 5, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr, 1, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 3, 0, 3),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal, 1, 0, 0),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr, 2, 0, 0),
  [179] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_param_list_repeat1, 2, 0, 0), SHIFT_REPEAT(112),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_param_list_repeat1, 2, 0, 0),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 4, 0, 3),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 5, 0, 3),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_list, 5, 0, 0),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [216] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_list, 6, 0, 0),
  [218] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_param_ty_list_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_param_ty_list_repeat1, 2, 0, 0),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_list, 2, 0, 0),
  [225] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_call_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [228] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_call_repeat1, 2, 0, 0),
  [230] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_param_list_repeat1, 4, 0, 0),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [304] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [308] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [310] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [312] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [316] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [318] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [320] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_tbl(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "tbl",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
